CREATE SCHEMA mailserver AUTHORIZATION mailadmin;

-- Creates aliases for emails e.g. postmaster.
CREATE TABLE
    IF NOT EXISTS mailserver.virtual_aliases (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        domain_id INTEGER REFERENCES mailserver.virtual_domains (id) ON DELETE CASCADE NOT NULL,
        source VARCHAR(100) NOT NULL,
        destination VARCHAR(100) NOT NULL
    );

CREATE TABLE
    IF NOT EXISTS mailserver.virtual_users (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        domain_id INTEGER REFERENCES mailserver.virtual_domains (id) ON DELETE CASCADE NOT NULL,
        email VARCHAR(100) NOT NULL UNIQUE,
        password VARCHAR(150) NOT NULL,
        quota BIGINT NOT NULL DEFAULT 0,
        -- To be used by tempmail service.
        temporary BOOLEAN DEFAULT FALSE
    );

CREATE TABLE
    IF NOT EXISTS mailserver.virtual_domains (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(50) NOT NULL
    );