// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MailserverVirtualAlias struct {
	ID          int32
	DomainID    int32
	Source      string
	Destination string
}

type MailserverVirtualDomain struct {
	ID   int32
	Name string
}

type MailserverVirtualUser struct {
	ID        int32
	DomainID  int32
	Email     string
	Password  string
	Quota     int64
	Temporary pgtype.Bool
}
