// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const createMailbox = `-- name: CreateMailbox :one
INSERT INTO
    mailserver.virtual_users (email, domain_id, password, temporary)
VALUES
    ($1, $2, $3, TRUE)
RETURNING id, domain_id, email, password, quota, temporary
`

type CreateMailboxParams struct {
	Email    string
	DomainID int32
	Password string
}

func (q *Queries) CreateMailbox(ctx context.Context, arg CreateMailboxParams) (MailserverVirtualUser, error) {
	row := q.db.QueryRow(ctx, createMailbox, arg.Email, arg.DomainID, arg.Password)
	var i MailserverVirtualUser
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Email,
		&i.Password,
		&i.Quota,
		&i.Temporary,
	)
	return i, err
}

const deleteMailbox = `-- name: DeleteMailbox :exec
DELETE FROM mailserver.virtual_users WHERE id = $1
`

func (q *Queries) DeleteMailbox(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMailbox, id)
	return err
}
